[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Air Hockey Challenge"
authors = [{name = "Puze Liu", email = "puze@robot-learning.de"}]
dynamic = ["version", "description"]
